org_name: Seminars Simulations Consulting Europe
contact_person: Sebastian Schäffer
street: Frauenfelderstraße 14/34
city_de: A-1170 Wien
city_en: A-1170 Vienna
email: info@ssc-europe.eu
phone_display: "+49 (0)30 65 79 12 50"
phone_tel: "+493065791250"
